apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    component: frontend
    project: roboshop
spec:
  replicas: 1
  selector:
    matchLabels:
      component: frontend
      project: roboshop
  template:
    metadata:
      labels:
        component: frontend
        project: roboshop
    spec:
      containers:
      - name: frontend
        image: 739561048503.dkr.ecr.us-east-1.amazonaws.com/frontend:TAG
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    component: frontend
    project: roboshop
spec:
  type: LoadBalancer
  selector:
    component: frontend
    project: roboshop
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
