componentName: frontend
image:
  component: frontend
health:
  path: /health
  port: "80"
service:
  type: LoadBalancer
  containerPort: 80
resources:
   limits:
     cpu: 500m
     memory: 512Mi
   requests:
     cpu: 500m
     memory: 512Mi
